### ISSUE TITLE
第五章settings文件拆分错误

### ISSUE THREAD

**Issue by libr1989** [the5fire/django-practice-book#14]
书中对于第五章django 的setting的拆分 缺少了一步，拆分后项目无法正常运行的
需要在settigns/__init__.py文件中加入from.base import *
from .develop import *
才能正常

**Comment by the5fire** [comment]
@libr1989  不用，你可能是拆分之后没有修改 manage.py 里面的代码。你看 85 页。

**Comment by leiaoo** [comment]
setting的拆分, 项目运行没有问题，但是在pychram中，打开python console后，会出现以下错误：
Traceback (most recent call last):
  File "<input>", line 6, in <module>
  File "D:\myProject\typeidea\lib\site-packages\django\__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "D:\myProject\typeidea\lib\site-packages\django\conf\__init__.py", line 79, in __getattr__
    self._setup(name)
  File "D:\myProject\typeidea\lib\site-packages\django\conf\__init__.py", line 64, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting LOGGING_CONFIG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.



在terminal中使用(typeidea) D:\myProject\typeidea>python manage.py shell 命令，出现以下错误：
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "D:\myProject\typeidea\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "D:\myProject\typeidea\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "D:\myProject\typeidea\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\myProject\typeidea\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "D:\myProject\typeidea\lib\site-packages\django\apps\config.py", line 116, in create
    mod = import_module(mod_path)
  File "C:\Program Files\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'blog'

以下是我manage.py的代码：

import os
import sys


def main():
    profile = os.environ.get('TYPEIDEA_PROFILE', 'develop')
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', f'typeidea.settings.{profile}')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()


我的目录结构是
![image](https://user-images.githubusercontent.com/8576385/60149277-bd05a400-9806-11e9-8001-9de730adcb3a.png)

**Comment by the5fire** [comment]
应该是 PyCharm 的问题，记得读者群有人反馈过，你可以进群交流：https://mp.weixin.qq.com/s?src=11&timestamp=1562024368&ver=1703&signature=QWlMvaRg3kgLygCHbjxqbAf5evJa4UwogMhsIqKQa8iGe5Fh54uqGQAU7RspoVXm*qQaOjXcm2NUko2SeGjnM*1BRapVj2uA72VK5NGRvUiD2ayE4Cw2OMGxaW57GouB&new=1

记得是需要设置下 root path

**Comment by libr1989** [comment]
好的，非常感谢


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: the5fire <notifications@github.com>
发送时间: Tuesday, July 2, 2019 7:40:06 AM
收件人: the5fire/django-practice-book <django-practice-book@noreply.github.com>
抄送: libr1989 <libr1989@live.com>; Mention <mention@noreply.github.com>
主题: Re: [the5fire/django-practice-book] 第五章settings文件拆分错误 (#14)


应该是 PyCharm 的问题，记得读者群有人反馈过，你可以进群交流：https://mp.weixin.qq.com/s?src=11&timestamp=1562024368&ver=1703&signature=QWlMvaRg3kgLygCHbjxqbAf5evJa4UwogMhsIqKQa8iGe5Fh54uqGQAU7RspoVXm*qQaOjXcm2NUko2SeGjnM*1BRapVj2uA72VK5NGRvUiD2ayE4Cw2OMGxaW57GouB&new=1

记得是需要设置下 root path

―

**Comment by xiaocui-iii** [comment]
作者，请问现在还有读者群吗
