### ISSUE TITLE
第二章节的代码都不能运行

### ISSUE THREAD

**Issue by dawnFromDark** [the5fire/django-practice-book#2]
socket_server.py
这个代码在anaconda上直接报错了，能够看下吗？

  File "d:\python_project\django-practice-book\code\chapter2\section2\socket_server.py", line 15, in <module>
    response = b'\r\n'.join(response_params)
TypeError: sequence item 0: expected a bytes-like object, str found

还有这个fork_server.py也报错，能够看下吗
pycd : 无法将“pycd”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ pycd 'd:\python_project\django-practice-book'; ${env:PYTHONIOENCODING ...
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (pycd:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
http://127.0.0.1:8000
Traceback (most recent call last):
  File "c:\Users\pengx\.vscode\extensions\ms-python.python-2019.1.0\pythonFiles\ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "c:\Users\pengx\.vscode\extensions\ms-python.python-2019.1.0\pythonFiles\lib\python\ptvsd\__main__.py", line 348, in main
    run()
  File "c:\Users\pengx\.vscode\extensions\ms-python.python-2019.1.0\pythonFiles\lib\python\ptvsd\__main__.py", line 253, in run_file
    runpy.run_path(target, run_name='__main__')
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\python_project\django-practice-book\code\chapter2\section2\fork_server.py", line 60, in <module>
    main()
  File "d:\python_project\django-practice-book\code\chapter2\section2\fork_server.py", line 49, in main
    conn, address = serversocket.accept()
  File "D:\ProgramData\Anaconda3\lib\socket.py", line 212, in accept
    fd, addr = self._accept()
BlockingIOError: [WinError 10035] 无法立即完成一个非阻止性套接字操作。

怎么一开始示例代码就不能运行啊

**Comment by dawnFromDark** [comment]
最起码的你代码得能够运行吧，不然你写本书不就是坑钱吗？
