### ISSUE TITLE
 settings文件拆分错误

### ISSUE THREAD

**Issue by leiaoo** [the5fire/django-practice-book#25]
setting的拆分, 项目运行没有问题，但是在pychram中，打开python console后，会出现以下错误：
Traceback (most recent call last):
File "", line 6, in
File "D:\myProject\typeidea\lib\site-packages\django_init_.py", line 19, in setup
configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
File "D:\myProject\typeidea\lib\site-packages\django\conf_init_.py", line 79, in getattr
self.setup(name)
File "D:\myProject\typeidea\lib\site-packages\django\conf_init.py", line 64, in _setup
% (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting LOGGING_CONFIG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

以下是我manage.py的代码：

import os
import sys

def main():
profile = os.environ.get('TYPEIDEA_PROFILE', 'develop')
os.environ.setdefault('DJANGO_SETTINGS_MODULE', f'typeidea.settings.{profile}')
try:
from django.core.management import execute_from_command_line
except ImportError as exc:
raise ImportError(
"Couldn't import Django. Are you sure it's installed and "
"available on your PYTHONPATH environment variable? Did you "
"forget to activate a virtual environment?"
) from exc
execute_from_command_line(sys.argv)

if name == 'main':
main()

我的目录结构是
![image](https://user-images.githubusercontent.com/8576385/60150384-18399580-980b-11e9-8318-b21e5e7792b4.png)

**Comment by leiaoo** [comment]
setting的拆分, 项目运行没有问题，但是在pychram中，打开python console后，会出现以下错误：
Traceback (most recent call last):
File "", line 6, in 
File "D:\myProject\typeidea\lib\site-packages\django_init_.py", line 19, in setup
configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
File "D:\myProject\typeidea\lib\site-packages\django\conf_init_.py", line 79, in getattr
self.setup(name)
File "D:\myProject\typeidea\lib\site-packages\django\conf_init.py", line 64, in _setup
% (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting LOGGING_CONFIG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

在terminal中使用(typeidea) D:\myProject\typeidea>python manage.py shell 命令，出现以下错误：
Traceback (most recent call last):
File "manage.py", line 22, in 
main()
File "manage.py", line 18, in main
execute_from_command_line(sys.argv)
File "D:\myProject\typeidea\lib\site-packages\django\core\management_init_.py", line 381, in execute_from_command_line
utility.execute()
File "D:\myProject\typeidea\lib\site-packages\django\core\management_init_.py", line 357, in execute
django.setup()
File "D:\myProject\typeidea\lib\site-packages\django_init_.py", line 24, in setup
apps.populate(settings.INSTALLED_APPS)
File "D:\myProject\typeidea\lib\site-packages\django\apps\registry.py", line 91, in populate
app_config = AppConfig.create(entry)
File "D:\myProject\typeidea\lib\site-packages\django\apps\config.py", line 116, in create
mod = import_module(mod_path)
File "C:\Program Files\Python36\lib\importlib_init_.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 994, in _gcd_import
File "", line 971, in _find_and_load
File "", line 941, in _find_and_load_unlocked
File "", line 219, in _call_with_frames_removed
File "", line 994, in _gcd_import
File "", line 971, in _find_and_load
File "", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'blog'

以下是我manage.py的代码：

import os
import sys

def main():
profile = os.environ.get('TYPEIDEA_PROFILE', 'develop')
os.environ.setdefault('DJANGO_SETTINGS_MODULE', f'typeidea.settings.{profile}')
try:
from django.core.management import execute_from_command_line
except ImportError as exc:
raise ImportError(
"Couldn't import Django. Are you sure it's installed and "
"available on your PYTHONPATH environment variable? Did you "
"forget to activate a virtual environment?"
) from exc
execute_from_command_line(sys.argv)

if name == 'main':
main()

我的目录结构是
![image](https://user-images.githubusercontent.com/8576385/60149442-474e0800-9807-11e9-8e5a-6b865065c6e5.png)

**Comment by the5fire** [comment]
没怎么用过 PyCharm，不过据群友反馈，需要设置 root path 才行。
